### ISSUE TITLE
missing optional argument crashes "comp use" node

### ISSUE THREAD

**Issue by rozek** [ollixx/node-red-contrib-components#25]
if a "comp start" node defines an optional property and this property will not be set in an assocaited "comp use" node, this node will crash upon evaluation

```
TypeError: Cannot read property 'length' of undefined
    at sendStartFlow (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/node-red-contrib-components/components/components.js:31:30)
    at component._inputCallback (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/node-red-contrib-components/components/components.js:242:7)
    at /Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26
    at Object.trigger (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/@node-red/util/lib/hooks.js:149:13)
    at component.Node._emitInput (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
    at component.Node.emit (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
    at component.Node.receive (/Users/andreas/Rozek/GitHub-free/node-red-within-express/node...
```

What I forgot: still setting the (optional!) parameter avoids the shown exception

[Edit] I may have some additional information about the bug: it seems as if the type of arguments MUST always be set properly in "comp use" nodes - even for optional ones. Sometimes, Node-RED displays an error triangle and refuses to deploy - but this is not always the case! Sometimes, it happens, that deployment succeeds even if "comp use" and "comp start" nodes have different argument types

**Comment by ollixx** [comment]
Thanks for reporting the bug. 

Regarding the red triangle: That is set only because of static validation, i.e. on startup, deployment or after changes in the editor are saved. The runtime validation of properties does not effect the node-red validation icon.

**Comment by ollixx** [comment]
fixed
